name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: optimize Clear
        run: php artisan optimize:clear   
      - name: optimize
        run: php artisan optimize  
      - name: view Clear
        run: php artisan view:clear         
      - name: route Clear
        run: php artisan route:clear        
      - name: cache Clear
        run: php artisan cache:clear     
      - name: confi route
        run: php artisan route:cache         
      - name: view config
        run: php artisan view:cache  
      - name: cache config
        run: php artisan config:cache 
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          password: ${{ secrets.FTP_PASSWORD }}
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          server-dir: /

